import Head from "next/head";
import React from "react";
import styles from "../../styles/Home.module.css";
import MealsComp from "../../components/Meals/MealsComp";

const Meals = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MealsComp />
    </div>
  );
};

export default Meals;
