import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { UsersModel } from "../types/usersTypeModel";

const Home: NextPage<{ users: UsersModel[] }> = ({ users }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {users.map((user: UsersModel) => (
          <div key={user.id}>
            <h1>{user.name}</h1>
          </div>
        ))}
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const users: UsersModel[] = await res.json();

  return {
    props: {
      users,
    },
  };
};

export default Home;
